services:
  frontend:
    build:
      context: ./client
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-https://tathya.api.obvix.cloud}
    ports:
      - "3007:3000"
    env_file:
      - ./client/.env
    depends_on:
      - backend
    networks:
      - tathya

  backend:
    build:
      context: ./server
    ports:
      - "8007:8007"
    env_file:
      - ./server/.env
    volumes:
      - upload_data:/app/data/uploads
    networks:
      - tathya

volumes:
  upload_data:

networks:
  tathya:
    driver: bridge
